export const topdata = {
  title: 'Eric',
  summary:
    "You are viewing details for the workspace 'Eric’s Workspace'. This workspace contains API collections, test flows, and environments that are organized for collaborative development and testing.",
  totalContributors: 10,
  totalCollections: 25,
  totalTestFLows: 3,
  totalEnvironments: 5,
  createdAt: '',
  updatedAt: '2 hours ago',
  updatedBy: 'Finn Doe',
};

export const ResourceData = {
  data: {
    hubs: [
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-23T10:45:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-30T15:20:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-05-08T09:10:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-19T17:35:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-05-06T12:50:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-28T08:30:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-05-01T13:15:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-21T11:00:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-05-03T14:40:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-26T18:25:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-29T16:05:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-05-05T09:55:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-17T10:10:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-05-02T07:45:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-20T19:30:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-05-04T11:20:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-25T14:10:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-22T13:50:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-04-27T15:00:00.000Z',
        createdBy: 'Film doe',
      },
      {
        resources: 'Collection',
        name: 'Auth Api',
        keystats: "8 Api's",
        updatedAt: '2025-05-07T10:30:00.000Z',
        createdBy: 'Film doe',
      },
    ],
  },
};

export const members = {
  data: [
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Viewer' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Editor' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Editor' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Editor' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
    { user: 'John Doe', Email: 'John.doe@gmail.com', roles: 'Admin' },
  ],
};
